config/routes.rb
Rails.application.routes.draw do
  get 'shopping_list/index'
  devise_for :users
  root 'user#index'
  get 'public_recipes/index'
  get 'shopping_list/index'
  resources :foods, only: [:index, :new, :create, :destroy]
  # resources :shopping_lists, only: [:index]

  # Defines the root path route ("/")
  # get "food#index"
  resources :recipes, only: [:index, :show, :new, :create, :destroy, :update] do 
    resources :food_recipes, only: [:new, :create, :edit, :update, :destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if (user.role = 'admin')
      can :manage, Food, user_id: user.id
      can :manage, Recipe, user_id: user.id
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  has_many :recipe_food
  has_many :recipes

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  has_many :recipe_food
  has_many :foods, through: :food_recipes
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, foreign_key: 'recipe_id'
  belongs_to :food, foreign_key: 'food_id'

  def total_value
    quantity * food.price
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods, dependent: :destroy
  validates :name, :email, presence: true
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: exception.message
  end
end

app/controllers/food_recipes_controller.rb
class FoodRecipesController < ApplicationController
  def index
    @food_recipes = RecipeFood.all
  end

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @food_recipe = RecipeFood.new
    respond_to do |format|
      format.html { render :new, locals: { recipe: @recipe, food_recipe: @food_recipe } }
    end
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @food_recipe = RecipeFood.find(params[:id])
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @food_recipe = RecipeFood.new(strong_params)
    @food_recipe.recipe = @recipe
    respond_to do |format|
      if @food_recipe.save!
        format.html do
          flash[:success] = 'Food recipe saved successfully'
          redirect_to recipe_path(params[:recipe_id])
        end
      else
        format.html do
          flash.now[:error] = 'Error: Food recipe could not be saved'
          render :new, locals: { recipe: @recipe, food_recipe: @food_recipe }
        end
      end
    end
  end

  def update
    @food_recipe = RecipeFood.find(params[:id])
    @food_recipe.update(modify_recipe_foods_param) # Pass the nested parameter here
    flash[:notice] = 'you have updated the recipe food'
    redirect_to recipe_path(params[:recipe_id])
  end

  def destroy
    @food_recipe = RecipeFood.find(params[:id])
    @recipe = @food_recipe.recipe
    @food_recipe.destroy!
    flash[:notice] = 'you have deleted the recipe food'
    redirect_to recipe_food_recipe_path(@recipe)
  end

  private

  def modify_recipe_foods_param
    params.require(:edit_food_recipe).permit(:quantity, :food_id)
  end

  def strong_params
    params.require(:food_recipe).permit(:quantity, :food_id)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource
  def index
    @food = Food.all
  end

  def new
    @food = Food.new
    respond_to do |format|
      format.html { render :new, locals: { food: @food } }
    end
  end

  def create
    @food = Food.new(food_params.merge(user_id: current_user.id))
    respond_to do |format|
      format.html do
        if @food.save!
          flash[:success] = 'food saved successfully'
          redirect_to foods_url
        else
          flash.now[:error] = 'Error: Food could not be saved'
          render :new, locals: { food: @food }
        end
      end
    end
  end

  def destroy
    @food = Food.find(params[:id])
    if @food.destroy
      flash[:success] = 'food deleted successfully'
      redirect_to foods_path
    else
      flash.now[:error] = 'Error: Food could not be delete'
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.includes(:recipe_food, :user).where('public = true').order(id: :desc)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @user = current_user
    @recipe = Recipe.new
    respond_to do |format|
      format.html { render :new, locals: { recipe: @recipe } }
    end
  end

  def create
    puts params.inspect
    @recipe = current_user.recipes.new(recipe_params)
    respond_to do |format|
      if @recipe.save!
        flash[:success] = 'Post saved successfully'
        format.html { redirect_to recipes_path }
      else
        flash.now[:error] = 'Error: Post could not be saved'
        format.html { render :new, locals: { recipe: @recipe } }
      end
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = 'Post successfully deleted'
    redirect_to recipes_path
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(public: !@recipe.public)
      flash[:notice] = "you updated the recipe status to #{'private' unless @recipe.public}"
    else
      flash[:error] = 'Error updating recipe status'
    end
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  def index
    # to show the recipe of the current user
    @recipes = Recipe.where(user_id: current_user.id)
    # get the foodlist of the recipe
    @recipe_foods = RecipeFood.where(recipe_id: @recipes.ids)
    # general food
    @foods = Food.where(id: @recipe_foods.pluck(:food_id))
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_recipes_helper.rb
module FoodRecipesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/food_recipes/edit.html.erb
<section class='food-form-container'>
<h1>Eidt ingredient to Recipe</h1>
<%= form_with url: recipe_food_recipe_path(@recipe.id, @food_recipe.id), scope: :edit_food_recipe, method: :patch do |form| %>

    <div class="form-div" >
    <div>
    <%= form.label :quantity, class:"form-label" %><br>
    <%= form.number_field :quantity ,  class:"form-control" , required: true, placeholder: '1',  min: 1%><br>
  </div>

  <div>
    <%= form.label :food, class:"form-label" %><br>
    <%= form.select :food_id, current_user.foods.map {|food| [food.name, food.id]},{ include_blank: true} , class:"form-select" %><br>
    </div>

  <div >
    <div class="mb-3 col-sm-1">
    <%= form.submit "Add", class:"btn btn-primary form-control" %>
    </div>
    </div>
  <%end%>
  <%=link_to 'Back', recipe_path(@recipe.id), class:"btn"%>
</section>

app/views/food_recipes/new.html.erb
<section class='food-form-container'>
<h1>Add ingredient to Recipe</h1>
<%= form_with url: recipe_food_recipes_path(recipe_id: @recipe.id), scope: :food_recipe do |form| %>
    <div class="form-div" >
    <div class='form-item'>
    <%= form.label :quantity, class:"form-label" %><br>
    <%= form.number_field :quantity , class:"input-form", required: true, placeholder: '1',  min: 1%><br>
  </div>

  <div class='form-item'>
    <%= form.label :food, class: 'form-label' %><br>
    <%= form.select :food_id, current_user.foods.map {|food| [food.name, food.id]},{ include_blank: true} , class:"input-form"%><br>
    </div>
  <div class='form-item'>
    <div>
    <%= form.submit "Add", class:"btn btn-primary form-control" %>
    </div>
    </div>
  <%end%>
<section>

app/views/foods/index.html.erb
<section>
<% if @food.blank? %>
<p>There are no foods items</p>
<% else %>
<table class='food-table'>
<thead>
    <tr>
      <th class="col">Food</th>
      <th class="col">Quantity</th>
      <th class="col">Measurement-Unit</th>
      <th class="col">Unit-Price</th>
      <th class="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @food.each do |food| %>
  <tr>
  <td><%= food.name %></td>
  <td><%= food.quantity %></td>
  <td><%= food.measurement_unit %> garams</td>
  <td>$<%= food.price %></td>
  <td><% if can? :destroy, food %>
  <%= button_to "Delete", food_path(food), method: :delete, class: "btn" %>
<% end %>

  </td>
  </tr>
  <% end %>
  <tbody>
</table>
<% end %>
<button class='btn'>
<%= link_to 'Post form', new_food_path %>
</button>

</section>

app/views/foods/new.html.erb
<section class='food-form-container'>
<h1>Add a new Food</h1>

<%= form_with model: @food, url: foods_path, method: :post, scope: :food, locals: { food: @food } do |form| %>

<div class='form-item'>
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class:"input-form" %>
</div>

<div class='form-item'>
      <%= form.label :measurement_unit, class: 'form-label' %>
      <%= form.text_field :measurement_unit, class:"input-form" %>
</div>

<div class='form-item'>
      <%= form.label :price, class: 'form-label' %>
      <%= form.text_field :price, class:"input-form" %>
</div>

<div class='form-item'>
      <%= form.label :quantity, class: 'form-label' %>
      <%= form.text_field :quantity, class:"input-form" %>
</div>

<%= form.submit "Add food" , class:"form-button" %>
  <% end %>

</section>

app/views/public_recipes/index.html.erb
<section>
<h1>Public Recipes</h1>
<% if @public_recipes.exists? %>
<% @public_recipes.each do |recipe| %>
<li>
<h1><%= link_to recipe.name, recipe_path(recipe) %></h1>
<p>by: <%= recipe.user.name %> </p>
<p>Total food items: <%= recipe.recipe_food.count %></p>
<% recipe.recipe_food.each  do |recipefoods| %>
<h6 class='total'>$ <%= recipefoods.quantity * recipefoods.food.price %></h6>
<% end %>
</li>
<% end %>
<% else %>
      <h2>No recipes availabale!!</h2>
     <% end %>  

     <button class='btn'>
<%= link_to 'back', recipes_path %>
</button>
</section>

app/views/recipes/index.html.erb
<section>
<h1>List of recipes</h1>
<button class='btn'><%= link_to 'Add new form', new_recipe_path %></button>
<ul class="recipe-section">
  <% @recipes.each do |recipe| %>
    <li>
      <h2><%= link_to recipe.name, {:action => 'show', :id => recipe.id } %></h2>
      <p><%= recipe.preparation_time %></p>
      <p><%= recipe.cooking_time %></p>
      <% if can? :destroy, recipe %>
        <%= button_to "Delete Recipe",  recipe_path(recipe), method: :delete, class: 'btn' %>
      <% end %>
      <p><%= recipe.description %></p>
    </li>
  <% end %>
</ul>
</section>

app/views/recipes/new.html.erb
<section class='food-form-container'>
<h1>New Recipe</h1>
<%= form_with model: @recipe, url: recipes_path do |form| %>
  <div class='form-item'>
    <%= form.label :name , class: 'form-label'%>
    <%= form.text_field :name, class:"input-form" %>
  </div>
  <div class='form-item'>
    <%= form.label :preparation_time , class: 'form-label' %>
    <%= form.text_field :preparation_time, class:"input-form" %>
  </div>
  <div class='form-item'>
    <%= form.label :cooking_time , class: 'form-label' %>
    <%= form.text_field :cooking_time, class:"input-form" %>
  </div>
  <div class='form-item'>
    <%= form.label :description , class: 'form-label' %>
    <%= form.text_area :description, class:"input-form" %>
  </div>   
<%= form.submit "Create Recipe", class:"input-form" %>
<% end %>
</section>

app/views/recipes/show.html.erb
<section class='recipe-show'>
<h1><%= @recipe.name %></h1>
<%= button_to recipe_path(@recipe.id), method: :patch do %>
  <% if @recipe.public %>
    <i class="fa-light fa-toggle-on btn-on"></i>
  <% else %>
    <i class="fa-light fa-toggle-off btn-off"></i>
  <% end %>
<% end %>
<p><strong>Preparation Time:</strong> <%= @recipe.preparation_time %> minutes</p>
<p><strong>Cooking Time:</strong> <%= @recipe.cooking_time %> minutes</p>
<p><%= @recipe.description %></p>
<p>Steps goes here.....</p>
<div class='btn-container' >
<button class='btn'>
<%= link_to 'Generate shopping list', shopping_list_index_path %>
</button>
<button class='btn'>
<%= link_to 'Add ingredient', new_recipe_food_recipe_path(@recipe.id)%>
</button>
</div>

<table class='food-table show'>
<thead>
<tr>
<th>Food</th>
<th>Quantity</th>
<th>Value</th>
<th>Actions</th>
</tr>
</thead>
<tbody>

<% @recipe.recipe_food.each do |recipe_food| %>
<tr>
<td><%= recipe_food.food.name %></td>
<td><%= recipe_food.food.quantity %> g</td>
<td><%= recipe_food.food.quantity * recipe_food.food.price %></td>
<td>
<% if can? :destroy, @recipe %>
<%= link_to 'modify', edit_recipe_food_recipe_path(@recipe.id, recipe_food.id) %>
<%= button_to 'delete', recipe_food_recipe_path(@recipe.id, recipe_food.id), method: :delete %>
<% end %>
</td>
</tr>
<% end %>
</tbody>
</table>

</section>

app/views/shopping_list/index.html.erb
<h1>Shopping List</h1>
<% if @foods.empty? %>
  <p>No items to purchase.</p>
<% else %>
  <ul>
  <div class="shopping-text">
  <p>The amount of food list : <%=@recipe_foods.count%></p>
  <p>Total value of food needed: <%= number_to_currency(@recipe_foods.sum(&:total_value)) %></p>
  </div>
  </ul>
<% end %>

<table class='food-table'>
<thead>
<tr>
<th>Food</th>
<th>Quantity</th>
<th>Price</th>

</tr>
</thead>
<tbody>

<% @foods.each do |recipe| %>
<tr>
<td><%= recipe.name %></td>
<td><%= recipe.quantity %>g</td>
<td><%= recipe.quantity * recipe.price %></td>


</tr>
<% end %>
</tbody>
</table>

app/views/user/index.html.erb
<section class='home-page'>
<h1>Welcome <%= @users.name %><h1>
<p>"Cooking is all about people. Food is maybe the only universal thing that really has the power to bring everyone together. No matter what culture, everywhere around the world, people get together to eat." - Guy Fieri</p>
</section>